#!/usr/bin/env python3
# =====================================================================
# fix.py: Robustly locate Section 3 and inject expanded Virtual Memory & MMU
# =====================================================================
import os
import re
import subprocess

EXPANDED_VM_HTML = """
    <!-- Section 3: Virtual Memory & The MMU -->
    <section id="virtual-memory-mmu" style="margin-bottom: 48px;">
      <h2>3. Virtual Memory &amp; The Memory Management Unit (MMU)</h2>
      <p>
        Early operating systems allocated physical memory contiguously. If an application requested 64 KiB, the operating system had to locate 64 KiB of uninterrupted physical RAM. This model suffered from severe memory fragmentation, made it impossible to run programs larger than physical memory, and provided zero memory safety: a rogue pointer could write directly into the operating system kernel or neighboring application memory.
      </p>
      <p>
        Modern architectures decouple the addresses generated by programs from the physical addresses wired into silicon using <strong>Virtual Memory</strong>, managed directly by specialized hardware called the <strong>Memory Management Unit (MMU)</strong>.
      </p>

      <h3>Virtual vs. Physical Address Spaces</h3>
      <p>
        Every user-mode application executes within its own private, isolated <strong>virtual address space</strong>. To the program, it appears as though it owns a massive, continuous block of memory (e.g., 4 GiB on 32-bit systems or 256 TiB in standard 48-bit x86-64 user space). The physical memory chips (DRAM), by contrast, are partitioned into fixed-size physical blocks called <strong>page frames</strong> (typically 4 KiB in size).
      </p>

      <div class="diagram-container">
        <!-- SVG Diagram: Virtual to Physical Mapping -->
        <svg viewBox="0 0 880 260" width="100%" height="auto" style="max-width: 880px; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;" xmlns="http://www.w3.org/2000/svg">
          <!-- Virtual Memory Strip -->
          <rect x="40" y="40" width="220" height="180" rx="6" fill="#f8fafc" stroke="#0284c7" stroke-width="2" />
          <text x="150" y="65" fill="#0284c7" font-size="13" font-weight="bold" text-anchor="middle">Virtual Address Space</text>
          <text x="150" y="82" fill="#64748b" font-size="10" text-anchor="middle">(Per-Process View: Continuous)</text>

          <rect x="55" y="100" width="190" height="28" rx="4" fill="#e0f2fe" stroke="#0284c7" />
          <text x="150" y="118" fill="#0369a1" font-size="11" text-anchor="middle">Page 0 (0x0000 - 0x0FFF)</text>

          <rect x="55" y="135" width="190" height="28" rx="4" fill="#e0f2fe" stroke="#0284c7" />
          <text x="150" y="153" fill="#0369a1" font-size="11" text-anchor="middle">Page 1 (0x1000 - 0x1FFF)</text>

          <rect x="55" y="170" width="190" height="28" rx="4" fill="#cbd5e1" stroke="#94a3b8" stroke-dasharray="4,2" />
          <text x="150" y="188" fill="#64748b" font-size="11" text-anchor="middle">Page 2 (Unmapped / Swapped)</text>

          <!-- MMU Translation Engine -->
          <rect x="340" y="70" width="180" height="120" rx="8" fill="#0284c7" stroke="#0369a1" stroke-width="2" />
          <text x="430" y="105" fill="#ffffff" font-size="14" font-weight="bold" text-anchor="middle">MMU</text>
          <text x="430" y="125" fill="#e0f2fe" font-size="11" text-anchor="middle">Hardware Translation</text>
          <text x="430" y="145" fill="#bae6fd" font-size="10" text-anchor="middle">TLB + Page Table Walk</text>
          <text x="430" y="165" fill="#ffffff" font-size="9" text-anchor="middle">Checks R/W/X Permissions</text>

          <!-- Physical Memory Strip -->
          <rect x="600" y="40" width="240" height="180" rx="6" fill="#f8fafc" stroke="#10b981" stroke-width="2" />
          <text x="720" y="65" fill="#059669" font-size="13" font-weight="bold" text-anchor="middle">Physical Memory (DRAM)</text>
          <text x="720" y="82" fill="#64748b" font-size="10" text-anchor="middle">(Non-Contiguous Page Frames)</text>

          <rect x="615" y="95" width="210" height="25" rx="4" fill="#f1f5f9" stroke="#cbd5e1" />
          <text x="720" y="112" fill="#64748b" font-size="10" text-anchor="middle">Frame 42 (Kernel Allocation)</text>

          <rect x="615" y="125" width="210" height="25" rx="4" fill="#d1fae5" stroke="#10b981" />
          <text x="720" y="142" fill="#065f46" font-size="10" font-weight="bold" text-anchor="middle">Frame 88 &larr; Virtual Page 0</text>

          <rect x="615" y="155" width="210" height="25" rx="4" fill="#f1f5f9" stroke="#cbd5e1" />
          <text x="720" y="172" fill="#64748b" font-size="10" text-anchor="middle">Frame 89 (Other App Frame)</text>

          <rect x="615" y="185" width="210" height="25" rx="4" fill="#d1fae5" stroke="#10b981" />
          <text x="720" y="202" fill="#065f46" font-size="10" font-weight="bold" text-anchor="middle">Frame 102 &larr; Virtual Page 1</text>

          <!-- Mapping Arrows -->
          <path d="M 245,114 L 340,114" fill="none" stroke="#0284c7" stroke-width="2" />
          <path d="M 245,149 L 340,140" fill="none" stroke="#0284c7" stroke-width="2" />
          <path d="M 520,114 L 615,137" fill="none" stroke="#10b981" stroke-width="2" />
          <path d="M 520,140 L 615,197" fill="none" stroke="#10b981" stroke-width="2" />
        </svg>
      </div>

      <h3>Address Translation Mechanics</h3>
      <p>
        A virtual memory address generated by the CPU is divided cleanly into two logical components:
      </p>
      <ul>
        <li><strong>Virtual Page Number (VPN):</strong> The upper address bits, which identify which page in the address space is being accessed.</li>
        <li><strong>Page Offset:</strong> The lower address bits, which specify the exact byte location within that 4 KiB page. Because 2<sup>12</sup> = 4096, standard 4 KiB pages use the lowest 12 bits as the offset.</li>
      </ul>
      <p>
        The hardware MMU takes the Virtual Page Number and indexes into the active process's <strong>Page Table</strong> to discover the corresponding <strong>Physical Frame Number (PFN)</strong>. The lowest 12 bits of the original address (the offset) pass through completely unmodified, because the byte offset within a virtual page is identical to the byte offset within a physical frame:
      </p>
      <div style="background: #0f172a; color: #f8fafc; padding: 14px 18px; border-radius: 6px; font-family: var(--font-mono); font-size: 0.88rem; margin: 16px 0;">
        Virtual Address:  [ Virtual Page Number (VPN) ] [ Page Offset (12 bits) ]<br>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&darr; (MMU Translation)<br>
        Physical Address: [ Physical Frame Number (PFN) ] [ Page Offset (12 bits) ]
      </div>

      <h3>Hierarchical Multi-Level Page Tables</h3>
      <p>
        If an operating system maintained a flat single-level table of 4 KiB pages across a 64-bit address space, the page table alone would require billions of gigabytes of RAM per process. Operating systems solve this by structuring page tables hierarchically as a multi-level tree (e.g., 4-level paging on x86-64 using PML4, PDPT, PD, and PT).
      </p>
      <p>
        The CPU maintains a dedicated control register—<strong>CR3 on x86-64</strong> or <strong>TTBR0/TTBR1 on ARM64</strong>—which holds the physical address of the root page table for the currently running process. If a range of virtual memory is unallocated, the entire subtree can be omitted, saving enormous amounts of physical RAM.
      </p>

      <h3>The Translation Lookaside Buffer (TLB)</h3>
      <p>
        Walking a 4-level page table requires up to 4 separate memory access cycles just to translate a single virtual address into a physical address before the actual data can be retrieved. To prevent memory access from slowing down by a factor of 5, the CPU features an on-die associative hardware cache called the <strong>Translation Lookaside Buffer (TLB)</strong>.
      </p>
      <ul>
        <li><strong>TLB Hit:</strong> The MMU checks the TLB in a single clock cycle. If the VPN is present, the physical frame is retrieved immediately, bypassing all page tables. Modern hit rates typically exceed 98%.</li>
        <li><strong>TLB Miss:</strong> The MMU hardware walks the multi-level page table in physical memory, loads the translation into the TLB, and completes the access.</li>
        <li><strong>Context Switches &amp; Flushes:</strong> Because each process maintains its own address space, reloading the root page table pointer (CR3) historically invalidated the entire TLB. Modern processors avoid this overhead using <strong>Address Space Identifiers (ASIDs)</strong> or <strong>Process-Context Identifiers (PCIDs)</strong>, tagging TLB entries with process IDs so cache lines persist across context switches.</li>
      </ul>

      <h3>Page Faults &amp; Demand Paging</h3>
      <p>
        Page table entries contain metadata status flags alongside the physical frame address:
      </p>
      <ul>
        <li><strong>Present Bit (P):</strong> 1 if the page resides in physical RAM; 0 if the page is unallocated or swapped out to storage.</li>
        <li><strong>Read/Write (R/W):</strong> Enforces read-only memory (e.g., executable code segments) vs. writable regions (heap/stack).</li>
        <li><strong>User/Supervisor (U/S):</strong> Prevents Ring 3 user programs from accessing kernel pages.</li>
        <li><strong>No-Execute (NX / XD):</strong> Prohibits executing instructions from data memory, mitigating buffer overflow attacks.</li>
      </ul>
      <p>
        When an application attempts to access a page whose Present Bit is 0, the MMU halts execution and triggers a <strong>Page Fault exception</strong> (Interrupt 14 on x86). The CPU saves execution registers and vectors into the kernel page fault handler:
      </p>
      <ol>
        <li>The kernel reads the faulting virtual address from processor register <strong>CR2</strong>.</li>
        <li>The kernel checks its internal memory maps: if the address is truly invalid, it sends a <code>SIGSEGV</code> (Segmentation Fault) or <code>STATUS_ACCESS_VIOLATION</code>.</li>
        <li>If the page is valid but swapped out (demand paging), the kernel allocates a free physical RAM frame, initiates a disk read from swap/backing storage, updates the page table entry with the new PFN, and sets the Present bit to 1.</li>
        <li>The kernel executes an exception return (<code>IRET</code>), prompting the CPU to re-execute the exact instruction that previously faulted—this time succeeding with a seamless TLB hit.</li>
      </ol>

      <!-- Interactive Directed Narrative Stepper: MMU & Address Translation -->
      <div id="interactive-mmu-simulator" style="margin: 32px 0; background: #ffffff; border: 1px solid #cbd5e1; border-radius: 8px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.05);">
        <!-- Header -->
        <div style="display: flex; justify-content: space-between; align-items: flex-start; flex-wrap: wrap; gap: 12px; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; margin-bottom: 18px;">
          <div>
            <h3 style="margin: 0; color: #0284c7; font-size: 1.15rem;">Guided Walkthrough: MMU Address Translation &amp; Page Fault Lifecycle</h3>
            <p style="margin: 4px 0 0 0; font-size: 0.85rem; color: #64748b;">Step through how CPU hardware and operating system routines resolve a memory access across silicon.</p>
          </div>

          <!-- Scenario Toggle -->
          <div style="display: flex; align-items: center; gap: 6px; background: #f1f5f9; padding: 4px; border-radius: 8px; border: 1px solid #cbd5e1;">
            <span style="font-family: var(--font-mono); font-size: 0.75rem; font-weight: 700; color: #475569; padding: 0 6px;">Scenario:</span>
            <button id="btn-mmu-tlb" class="mmu-toggle-btn active" style="padding: 5px 12px; font-family: var(--font-mono); font-size: 0.8rem; font-weight: 700; border-radius: 5px; border: none; background: #0284c7; color: #ffffff; cursor: pointer; transition: all 0.15s ease;">TLB Miss &amp; Walk</button>
            <button id="btn-mmu-fault" class="mmu-toggle-btn" style="padding: 5px 12px; font-family: var(--font-mono); font-size: 0.8rem; font-weight: 700; border-radius: 5px; border: none; background: transparent; color: #475569; cursor: pointer; transition: all 0.15s ease;">Page Fault &amp; Swap</button>
          </div>
        </div>

        <!-- Instructions Guide -->
        <div style="background: #f1f5f9; border: 1px solid #cbd5e1; border-radius: 6px; padding: 14px 18px; margin-bottom: 16px;">
          <div style="font-family: var(--font-mono); font-size: 0.78rem; font-weight: 700; color: #0369a1; text-transform: uppercase; margin-bottom: 6px;">How to Use This Simulator</div>
          <ol style="margin-left: 20px; margin-bottom: 0; color: #334155; font-size: 0.88rem; line-height: 1.5;">
            <li><strong>Choose a Scenario:</strong> Select between a standard <code>TLB Miss &amp; Page Walk</code> or an operating system <code>Page Fault &amp; Swap</code> resolution.</li>
            <li><strong>Follow the Next Step Preview:</strong> Read the adjacent upcoming action card to anticipate the hardware or kernel state transition before clicking <code>Next Step &rarr;</code>.</li>
            <li><strong>Inspect the Telemetry Bar:</strong> Watch the <strong>Virtual Address</strong> decompose into <strong>VPN</strong> and <strong>Offset</strong>, and watch the physical translation materialize.</li>
          </ol>
        </div>

        <!-- Controls & Adjacent Next Step Card -->
        <div style="display: grid; grid-template-columns: auto 1fr; gap: 16px; align-items: stretch; background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 6px; padding: 14px; margin-bottom: 20px;">
          <div style="display: flex; flex-direction: column; gap: 8px; justify-content: center; min-width: 170px;">
            <button id="mmu-next-btn" style="padding: 10px 16px; font-family: var(--font-mono); font-size: 0.85rem; font-weight: 700; border-radius: 6px; border: 1px solid #0284c7; background: #0284c7; color: #ffffff; cursor: pointer; text-align: center; transition: all 0.15s ease;">Next Step &rarr;</button>
            <div style="display: flex; gap: 8px;">
              <button id="mmu-prev-btn" style="flex: 1; padding: 6px 10px; font-family: var(--font-mono); font-size: 0.8rem; font-weight: 600; border-radius: 6px; border: 1px solid #cbd5e1; background: #ffffff; color: #475569; cursor: pointer;">&larr; Prev</button>
              <button id="mmu-reset-btn" style="flex: 1; padding: 6px 10px; font-family: var(--font-mono); font-size: 0.8rem; border-radius: 6px; border: 1px solid #cbd5e1; background: #ffffff; color: #64748b; cursor: pointer;">Reset</button>
            </div>
          </div>

          <div style="background: #f0f9ff; border: 1px solid #bae6fd; border-left: 4px solid #0284c7; border-radius: 0 6px 6px 0; padding: 10px 14px; display: flex; flex-direction: column; justify-content: center;">
            <div style="font-family: var(--font-mono); font-size: 0.72rem; font-weight: 700; color: #0369a1; text-transform: uppercase; letter-spacing: 0.03em;">Upcoming Action When You Click Next:</div>
            <div id="mmu-inline-next-desc" style="font-size: 0.88rem; color: #0c4a6e; line-height: 1.45; margin-top: 4px;">Loading step information...</div>
          </div>
        </div>

        <!-- Telemetry State Bar -->
        <div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(135px, 1fr)); gap: 10px; margin-bottom: 20px; font-family: var(--font-mono); font-size: 0.8rem;">
          <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 12px;">
            <div style="color: #64748b; font-size: 0.72rem; text-transform: uppercase;">Virtual Address</div>
            <div id="mmu-status-vaddr" style="font-weight: 700; color: #0f172a; margin-top: 2px;">0x00403018</div>
          </div>
          <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 12px;">
            <div style="color: #64748b; font-size: 0.72rem; text-transform: uppercase;">VPN / Offset</div>
            <div id="mmu-status-vpn" style="font-weight: 700; color: #0284c7; margin-top: 2px;">VPN: 0x00403 | 0x018</div>
          </div>
          <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 12px;">
            <div style="color: #64748b; font-size: 0.72rem; text-transform: uppercase;">TLB State</div>
            <div id="mmu-status-tlb" style="font-weight: 700; color: #dc2626; margin-top: 2px;">MISS</div>
          </div>
          <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 12px;">
            <div style="color: #64748b; font-size: 0.72rem; text-transform: uppercase;">Present Bit</div>
            <div id="mmu-status-present" style="font-weight: 700; color: #166534; margin-top: 2px;">1 (Resident)</div>
          </div>
          <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 6px; padding: 8px 12px;">
            <div style="color: #64748b; font-size: 0.72rem; text-transform: uppercase;">Physical Address</div>
            <div id="mmu-status-paddr" style="font-weight: 700; color: #0369a1; margin-top: 2px;">Resolving...</div>
          </div>
        </div>

        <!-- SVG Architecture Canvas -->
        <div style="display: flex; justify-content: center; margin-bottom: 20px; overflow-x: auto;">
          <svg id="mmu-anim-svg" viewBox="0 0 940 280" width="100%" height="auto" style="max-width: 940px; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;" xmlns="http://www.w3.org/2000/svg">
            <!-- Interconnect Bus Bar -->
            <rect x="25" y="130" width="890" height="20" rx="4" fill="#e2e8f0" stroke="#94a3b8" stroke-width="1.5" />
            <text x="470" y="144" fill="#475569" font-size="10" font-weight="700" text-anchor="middle">INTERNAL CPU &amp; SYSTEM MEMORY BUS</text>

            <!-- Node 1: CPU Core (x: 25, w: 165) -->
            <g id="mmu-node-cpu" transform="translate(25, 30)">
              <rect x="0" y="0" width="165" height="65" rx="6" fill="#ffffff" stroke="#cbd5e1" stroke-width="1.5" />
              <text x="82" y="24" fill="#0f172a" font-size="11" font-weight="700" text-anchor="middle">1. CPU Execution</text>
              <text x="82" y="42" fill="#64748b" font-size="9.5" text-anchor="middle">Issues Memory Load</text>
              <text id="mmu-node1-val" x="82" y="56" fill="#0284c7" font-size="9" text-anchor="middle">VA: 0x00403018</text>
            </g>

            <!-- Node 2: TLB Cache (x: 210, w: 165) -->
            <g id="mmu-node-tlb" transform="translate(210, 30)">
              <rect x="0" y="0" width="165" height="65" rx="6" fill="#ffffff" stroke="#cbd5e1" stroke-width="1.5" />
              <text x="82" y="24" fill="#0f172a" font-size="11" font-weight="700" text-anchor="middle">2. On-Die TLB</text>
              <text id="mmu-node2-state" x="82" y="42" fill="#64748b" font-size="9.5" text-anchor="middle">Associative Lookup</text>
              <text id="mmu-node2-tag" x="82" y="56" fill="#0284c7" font-size="9" text-anchor="middle">Check Tag for VPN</text>
            </g>

            <!-- Node 3: Page Table Walker / MMU (x: 395, w: 165) -->
            <g id="mmu-node-ptw" transform="translate(395, 30)">
              <rect x="0" y="0" width="165" height="65" rx="6" fill="#ffffff" stroke="#cbd5e1" stroke-width="1.5" />
              <text id="mmu-node3-title" x="82" y="24" fill="#0f172a" font-size="11" font-weight="700" text-anchor="middle">3. Page Table Walk</text>
              <text id="mmu-node3-sub" x="82" y="42" fill="#64748b" font-size="9.5" text-anchor="middle">CR3 Root Pointer</text>
              <text id="mmu-node3-detail" x="82" y="56" fill="#0284c7" font-size="9" text-anchor="middle">Reads Multi-Level PT</text>
            </g>

            <!-- Node 4: Physical DRAM (x: 580, w: 165) -->
            <g id="mmu-node-ram" transform="translate(580, 30)">
              <rect x="0" y="0" width="165" height="65" rx="6" fill="#ffffff" stroke="#cbd5e1" stroke-width="1.5" />
              <text id="mmu-node4-title" x="82" y="24" fill="#0f172a" font-size="11" font-weight="700" text-anchor="middle">4. Physical RAM</text>
              <text id="mmu-node4-sub" x="82" y="42" fill="#64748b" font-size="9.5" text-anchor="middle">Target Page Frame</text>
              <text id="mmu-node4-detail" x="82" y="56" fill="#0284c7" font-size="9" text-anchor="middle">Frame: 0x07B4000</text>
            </g>

            <!-- Node 5: Disk Backing Store / Swap (x: 765, w: 150) -->
            <g id="mmu-node-disk" transform="translate(765, 30)">
              <rect x="0" y="0" width="150" height="65" rx="6" fill="#ffffff" stroke="#cbd5e1" stroke-width="1.5" />
              <text id="mmu-node5-title" x="75" y="24" fill="#0f172a" font-size="11" font-weight="700" text-anchor="middle">5. Swap / Disk</text>
              <text id="mmu-node5-sub" x="75" y="42" fill="#64748b" font-size="9.5" text-anchor="middle">Backing Store File</text>
              <text id="mmu-node5-detail" x="75" y="56" fill="#0284c7" font-size="9" text-anchor="middle">Inactive in Hit</text>
            </g>

            <!-- Vertical Bus Drop Lines -->
            <line id="mmu-line-1" x1="107" y1="95" x2="107" y2="130" stroke="#cbd5e1" stroke-width="2" />
            <line id="mmu-line-2" x1="292" y1="95" x2="292" y2="130" stroke="#cbd5e1" stroke-width="2" />
            <line id="mmu-line-3" x1="477" y1="95" x2="477" y2="130" stroke="#cbd5e1" stroke-width="2" />
            <line id="mmu-line-4" x1="662" y1="95" x2="662" y2="130" stroke="#cbd5e1" stroke-width="2" />
            <line id="mmu-line-5" x1="840" y1="95" x2="840" y2="130" stroke="#cbd5e1" stroke-width="2" />

            <!-- Dynamic Bottom Mapping Console -->
            <g transform="translate(25, 175)">
              <rect x="0" y="0" width="890" height="85" rx="6" fill="#f8fafc" stroke="#cbd5e1" />
              <text x="20" y="25" fill="#0369a1" font-size="11" font-weight="700">ACTIVE TRANSLATION STAGE</text>
              <text id="mmu-flow-title" x="20" y="48" fill="#0f172a" font-size="11" font-family="var(--font-mono)">
                CPU issues virtual load &rarr; MMU evaluates TLB tag cache.
              </text>
              <text id="mmu-flow-sub" x="20" y="68" fill="#64748b" font-size="10" font-family="var(--font-mono)">
                Initial request staged. Checking on-die cache lines.
              </text>
            </g>
          </svg>
        </div>

        <!-- Paired Analytical Panes -->
        <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 14px;">
          <!-- What Is Happening -->
          <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-left: 4px solid #0284c7; padding: 16px; border-radius: 0 6px 6px 0;">
            <div style="font-family: var(--font-mono); font-size: 0.75rem; font-weight: 700; color: #0284c7; text-transform: uppercase; letter-spacing: 0.03em;">What Is Happening</div>
            <div id="mmu-desc-what" style="font-size: 0.9rem; color: #1e293b; line-height: 1.55; margin-top: 8px;"></div>
          </div>

          <!-- Why The System Does This -->
          <div style="background: #f8fafc; border: 1px solid #cbd5e1; border-left: 4px solid #10b981; padding: 16px; border-radius: 0 6px 6px 0;">
            <div style="font-family: var(--font-mono); font-size: 0.75rem; font-weight: 700; color: #059669; text-transform: uppercase; letter-spacing: 0.03em;">Why The System Does This</div>
            <div id="mmu-desc-why" style="font-size: 0.9rem; color: #1e293b; line-height: 1.55; margin-top: 8px;"></div>
          </div>
        </div>
      </div>

      <script>
        (function() {
          const mmuScenarios = {
            tlb: [
              {
                vaddr: "0x00403018",
                vpn: "VPN: 0x00403 | Off: 0x018",
                tlb: "CHECKING...",
                present: "Unknown",
                paddr: "Translating...",
                activeNode: "mmu-node-cpu",
                activeLine: "mmu-line-1",
                btnNextText: "Next: Query TLB Cache &rarr;",
                btnPrevText: "&larr; Prev",
                inlineNext: "The MMU will query the Translation Lookaside Buffer (TLB) tag associative array to check for a cached translation.",
                flowTitle: "INSTRUCTION FETCH &rarr; Splitting Virtual Address into VPN and Offset",
                flowSub: "The CPU pipeline decodes MOV EAX, [0x00403018]. Address bits [47:12] define the VPN; bits [11:0] define the offset.",
                what: "A user thread executes a load instruction from heap address <code>0x00403018</code>. The CPU pipeline passes the 48-bit virtual address to the on-die MMU. The MMU separates the address into a <strong>Virtual Page Number (0x00403)</strong> and a <strong>12-bit Page Offset (0x018)</strong>.",
                why: "Decoupling the page number from the byte offset allows the hardware to manage memory allocation in coarse 4 KiB chunks while retaining single-byte addressing precision."
              },
              {
                vaddr: "0x00403018",
                vpn: "VPN: 0x00403 | Off: 0x018",
                tlb: "MISS (Tag Absent)",
                present: "Unknown",
                paddr: "Translating...",
                activeNode: "mmu-node-tlb",
                activeLine: "mmu-line-2",
                btnNextText: "Next: Walk Page Tables &rarr;",
                btnPrevText: "&larr; Prev",
                inlineNext: "The hardware MMU will load the root page table pointer from register CR3 and walk the hierarchical page directory in RAM.",
                flowTitle: "TLB TAG EVALUATION &rarr; Cache Miss Detected",
                flowSub: "VPN 0x00403 is not in the L1/L2 TLB. MMU must initiate a hardware page table walk.",
                what: "The MMU queries its high-speed Translation Lookaside Buffer (TLB). The tag comparison does not find VPN <code>0x00403</code> in cache. The MMU flags a <strong>TLB Miss</strong> and triggers the hardware page table walker.",
                why: "The TLB is small (typically 64 to 1536 entries) to maintain single-cycle latency. When an address has not been accessed recently, the system must fall back to main memory page tables."
              },
              {
                vaddr: "0x00403018",
                vpn: "VPN: 0x00403 | Off: 0x018",
                tlb: "MISS (Walking PT)",
                present: "1 (Valid &amp; Resident)",
                paddr: "Base: 0x07B40000",
                activeNode: "mmu-node-ptw",
                activeLine: "mmu-line-3",
                btnNextText: "Next: Compute Physical Address &rarr;",
                btnPrevText: "&larr; Prev",
                inlineNext: "The MMU will combine the Physical Frame Number (0x07B40) with the original offset (0x018) and update the TLB.",
                flowTitle: "PAGE DIRECTORY WALK &rarr; Reading PML4 &rarr; PDPT &rarr; PD &rarr; PT Entries",
                flowSub: "CR3 locates root table in RAM. MMU verifies Present=1 and User/Supervisor=1 flags.",
                what: "The hardware MMU reads the base of the root page table from register <strong>CR3</strong>. It traverses the 4-level page hierarchy in DRAM. At the final Page Table Entry (PTE), it finds <strong>Physical Frame Number 0x07B40</strong> with the <strong>Present Bit = 1</strong> and Read/Write flags set.",
                why: "Hierarchical page tables allow the operating system to leave unallocated regions unpopulated, preventing empty address space from consuming physical memory."
              },
              {
                vaddr: "0x00403018",
                vpn: "VPN: 0x00403 | Off: 0x018",
                tlb: "CACHED (Warm)",
                present: "1 (Valid)",
                paddr: "0x07B40018 (Resolved)",
                activeNode: "mmu-node-ram",
                activeLine: "mmu-line-4",
                btnNextText: "Restart Scenario &#8634;",
                btnPrevText: "&larr; Prev",
                inlineNext: "Translation complete. Future accesses to this page will hit the TLB in a single clock cycle.",
                flowTitle: "PHYSICAL ACCESS &rarr; Appending 12-bit Offset &amp; Inserting TLB Line",
                flowSub: "Physical address 0x07B40018 issued over memory bus. DRAM returns 32-bit word.",
                what: "The MMU combines the Physical Frame Number (<code>0x07B40000</code>) with the original offset (<code>0x018</code>) to formulate physical address <code>0x07B40018</code>. It automatically inserts this translation into the TLB and reads the data from DRAM into CPU registers.",
                why: "By inserting the new mapping into the TLB, the next instruction accessing any byte within this 4 KiB page will complete with a single-cycle TLB hit, avoiding any page table walks."
              }
            ],
            fault: [
              {
                vaddr: "0x00705020",
                vpn: "VPN: 0x00705 | Off: 0x020",
                tlb: "MISS",
                present: "0 (Not in RAM)",
                paddr: "None (P=0)",
                activeNode: "mmu-node-cpu",
                activeLine: "mmu-line-1",
                btnNextText: "Next: Walk Page Table &rarr;",
                btnPrevText: "&larr; Prev",
                inlineNext: "The MMU will walk the page table and discover the Present bit is 0, indicating the page is not in physical memory.",
                flowTitle: "MEMORY LOAD &rarr; Referencing Cold / Swapped Page",
                flowSub: "Application references address 0x00705020. Data currently resides in storage swap.",
                what: "A process accesses address <code>0x00705020</code> in a memory-mapped file or swapped heap region. The MMU splits the address into VPN <code>0x00705</code> and offset <code>0x020</code>.",
                why: "Operating systems overcommit memory: inactive pages are evicted to disk so active processes can utilize fast physical DRAM."
              },
              {
                vaddr: "0x00705020",
                vpn: "VPN: 0x00705 | Off: 0x020",
                tlb: "MISS",
                present: "0 (Triggers Fault)",
                paddr: "TRAP to Kernel",
                activeNode: "mmu-node-ptw",
                activeLine: "mmu-line-3",
                btnNextText: "Next: Fire Page Fault (Int 14) &rarr;",
                btnPrevText: "&larr; Prev",
                inlineNext: "The CPU will halt execution, store the faulting address into register CR2, and switch to kernel mode via Interrupt 14.",
                flowTitle: "PTE INSPECTION &rarr; Present Bit = 0 Detected",
                flowSub: "MMU halts memory access. Hardware raises Page Fault Exception (Interrupt 14).",
                what: "The MMU walks the page table and inspects the PTE. The <strong>Present Bit is 0</strong>. The MMU halts execution, saves the faulting address <code>0x00705020</code> into register <strong>CR2</strong>, and triggers an architectural Page Fault Exception (Interrupt 14).",
                why: "Hardware cannot read files or swap partitions; only the operating system kernel contains filesystems and storage drivers. The MMU must trap into supervisor code to handle the missing frame."
              },
              {
                vaddr: "0x00705020",
                vpn: "VPN: 0x00705 | Off: 0x020",
                tlb: "BYPASSED",
                present: "0 (I/O in Progress)",
                paddr: "Allocating Frame...",
                activeNode: "mmu-node-disk",
                activeLine: "mmu-line-5",
                btnNextText: "Next: Swap In from Storage &rarr;",
                btnPrevText: "&larr; Prev",
                inlineNext: "The kernel disk driver will allocate a free physical frame and stream the 4 KiB page from storage into RAM.",
                flowTitle: "KERNEL PAGE FAULT HANDLER &rarr; Swap File / Backing Store Read",
                flowSub: "OS allocates physical Frame 0x09210 and initiates storage controller transfer.",
                what: "The kernel page fault handler reads CR2, verifies the address is valid in the process memory descriptor, allocates an available physical RAM frame (<code>0x09210</code>), and issues a block read command to storage.",
                why: "Demand paging allows systems to run programs that exceed physical RAM capacity by keeping only active working-set pages in high-speed memory."
              },
              {
                vaddr: "0x00705020",
                vpn: "VPN: 0x00705 | Off: 0x020",
                tlb: "INVALIDATED",
                present: "1 (PTE Updated)",
                paddr: "0x09210020",
                activeNode: "mmu-node-ram",
                activeLine: "mmu-line-4",
                btnNextText: "Next: Retry Instruction &rarr;",
                btnPrevText: "&larr; Prev",
                inlineNext: "The kernel will execute IRET, causing the CPU to transparently re-execute the exact instruction that previously faulted.",
                flowTitle: "PTE UPDATE &rarr; Setting Present=1 &amp; Issuing IRET",
                flowSub: "PTE points to Frame 0x09210. CPU returns to user mode and restarts instruction.",
                what: "The storage transfer completes. The kernel writes Physical Frame <code>0x09210</code> into the PTE, sets the <strong>Present Bit = 1</strong>, invalidates any stale TLB lines, and executes <code>IRET</code>. The CPU re-executes the original load instruction, which now succeeds immediately.",
                why: "The entire fault, disk transfer, and page allocation is completely transparent to the user program. The application simply experiences a brief stall before resuming normal execution."
              }
            ]
          };

          let currentScenario = "tlb";
          let stepIndex = 0;

          function renderMMUState() {
            const data = mmuScenarios[currentScenario][stepIndex];
            document.getElementById("mmu-status-vaddr").textContent = data.vaddr;
            document.getElementById("mmu-status-vpn").textContent = data.vpn;
            document.getElementById("mmu-status-tlb").textContent = data.tlb;
            document.getElementById("mmu-status-present").innerHTML = data.present;
            document.getElementById("mmu-status-paddr").textContent = data.paddr;

            document.getElementById("mmu-inline-next-desc").innerHTML = data.inlineNext;
            document.getElementById("mmu-desc-what").innerHTML = data.what;
            document.getElementById("mmu-desc-why").innerHTML = data.why;

            document.getElementById("mmu-flow-title").innerHTML = data.flowTitle;
            document.getElementById("mmu-flow-sub").innerHTML = data.flowSub;

            const nextBtn = document.getElementById("mmu-next-btn");
            const prevBtn = document.getElementById("mmu-prev-btn");

            if (nextBtn) nextBtn.innerHTML = data.btnNextText;
            if (prevBtn) {
              prevBtn.innerHTML = data.btnPrevText;
              prevBtn.style.opacity = stepIndex === 0 ? "0.5" : "1.0";
              prevBtn.style.cursor = stepIndex === 0 ? "not-allowed" : "pointer";
            }

            const allNodes = ["mmu-node-cpu", "mmu-node-tlb", "mmu-node-ptw", "mmu-node-ram", "mmu-node-disk"];
            allNodes.forEach(id => {
              const el = document.getElementById(id);
              if (el) {
                const rect = el.querySelector("rect");
                if (rect) {
                  rect.setAttribute("stroke", "#cbd5e1");
                  rect.setAttribute("stroke-width", "1.5");
                  rect.setAttribute("fill", "#ffffff");
                }
              }
            });

            const allLines = ["mmu-line-1", "mmu-line-2", "mmu-line-3", "mmu-line-4", "mmu-line-5"];
            allLines.forEach(id => {
              const el = document.getElementById(id);
              if (el) {
                el.setAttribute("stroke", "#cbd5e1");
                el.setAttribute("stroke-width", "2");
              }
            });

            const activeNodeEl = document.getElementById(data.activeNode);
            if (activeNodeEl) {
              const rect = activeNodeEl.querySelector("rect");
              if (rect) {
                rect.setAttribute("stroke", "#0284c7");
                rect.setAttribute("stroke-width", "2.5");
                rect.setAttribute("fill", "#f0f9ff");
              }
            }

            const activeLineEl = document.getElementById(data.activeLine);
            if (activeLineEl) {
              activeLineEl.setAttribute("stroke", "#0284c7");
              activeLineEl.setAttribute("stroke-width", "3");
            }
          }

          function setMMUScenario(scenarioKey) {
            currentScenario = scenarioKey;
            stepIndex = 0;
            const btnTLB = document.getElementById("btn-mmu-tlb");
            const btnFault = document.getElementById("btn-mmu-fault");
            if (scenarioKey === "tlb") {
              btnTLB.style.background = "#0284c7";
              btnTLB.style.color = "#ffffff";
              btnFault.style.background = "transparent";
              btnFault.style.color = "#475569";
            } else {
              btnFault.style.background = "#0284c7";
              btnFault.style.color = "#ffffff";
              btnTLB.style.background = "transparent";
              btnTLB.style.color = "#475569";
            }
            renderMMUState();
          }

          document.getElementById("btn-mmu-tlb").addEventListener("click", () => setMMUScenario("tlb"));
          document.getElementById("btn-mmu-fault").addEventListener("click", () => setMMUScenario("fault"));

          document.getElementById("mmu-next-btn").addEventListener("click", function() {
            if (stepIndex < mmuScenarios[currentScenario].length - 1) {
              stepIndex++;
            } else {
              stepIndex = 0;
            }
            renderMMUState();
          });

          document.getElementById("mmu-prev-btn").addEventListener("click", function() {
            if (stepIndex > 0) {
              stepIndex--;
              renderMMUState();
            }
          });

          document.getElementById("mmu-reset-btn").addEventListener("click", function() {
            stepIndex = 0;
            renderMMUState();
          });

          renderMMUState();
        })();
      </script>
    </section>
"""

def execute_replacement():
    file_path = os.path.join("week01-operating-system-concepts", "02-hardware-review.html")
    if not os.path.exists(file_path):
        print(f"Error: {file_path} not found.")
        return

    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Determine start of Section 3 (Virtual Memory or Memory Hierarchy)
    sec3_match = re.search(r'(<!-- Section 3.*?-->\s*<section.*?>|<section id="[^"]*memory[^"]*">|<section id="virtual-memory-mmu">|<h2>3\.[^<]*</h2>)', content, flags=re.IGNORECASE)

    # Determine start of Section 4 (I/O Devices)
    sec4_match = re.search(r'(<!-- Section 4.*?-->\s*<section|<section id="io-devices"|<section id="[^"]*io[^"]*">|<h2>4\.[^<]*</h2>)', content, flags=re.IGNORECASE)

    if sec3_match and sec4_match and sec3_match.start() < sec4_match.start():
        start_idx = sec3_match.start()
        end_idx = sec4_match.start()
        print(f"--> Found Section 3 boundary from index {start_idx} to {end_idx}.")
        content = content[:start_idx] + EXPANDED_VM_HTML.strip() + "\n\n    " + content[end_idx:]
    else:
        # Fallback: search for Virtual Memory subsection
        vm_sub_match = re.search(r'<h3>Virtual Memory</h3>.*?(?=<h3>|<h2>|</section>)', content, flags=re.DOTALL)
        if vm_sub_match:
            print("--> Found <h3>Virtual Memory</h3> subsection; substituting.")
            start_idx, end_idx = vm_sub_match.span()
            content = content[:start_idx] + EXPANDED_VM_HTML.strip() + content[end_idx:]
        else:
            print("--> Could not locate Section 3 boundaries. Searching headings:")
            for m in re.finditer(r'<h[23][^>]*>.*?</h[23]>', content):
                print("   Found heading:", m.group(0))
            return

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    print("--> File written successfully.")

    try:
        subprocess.run(["git", "add", "fix.py", file_path], check=True)
        commit_msg = (
            "Expand Virtual Memory & MMU with interactive translation stepper widget\n\n"
            "Locate Section 3 boundaries in 02-hardware-review.html and inject the\n"
            "expanded paging, TLB, page fault theory and interactive narrative stepper."
        )
        subprocess.run(["git", "commit", "-m", commit_msg], check=True)
        subprocess.run(["git", "push", "origin", "main"], check=True)
        print("--> Git sync completed successfully via fix.py!")
    except Exception as e:
        print(f"Git execution note: {e}")

if __name__ == "__main__":
    execute_replacement()
