#!/usr/bin/env python3
# =====================================================================
# fix.py: Shift bottom physical address boxes down in translation SVG
# =====================================================================
import os
import re
import subprocess

REFINED_ADDRESS_SPLIT_SVG = """
      <div class="diagram-container" style="margin: 24px 0;">
        <svg viewBox="0 0 880 260" width="100%" height="auto" style="max-width: 880px; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <marker id="arrowBlue" markerWidth="6" markerHeight="6" refX="4" refY="3" orient="auto">
              <path d="M0,0 L6,3 L0,6 Z" fill="#0284c7" />
            </marker>
            <marker id="arrowGreen" markerWidth="6" markerHeight="6" refX="4" refY="3" orient="auto">
              <path d="M0,0 L6,3 L0,6 Z" fill="#059669" />
            </marker>
            <marker id="arrowGray" markerWidth="6" markerHeight="6" refX="4" refY="3" orient="auto">
              <path d="M0,0 L6,3 L0,6 Z" fill="#64748b" />
            </marker>
          </defs>

          <!-- Top Label -->
          <text x="40" y="24" fill="#0f172a" font-size="12" font-weight="700">VIRTUAL ADDRESS (Generated by CPU Instruction)</text>

          <!-- Virtual Address Split Boxes -->
          <!-- VPN Box -->
          <rect x="40" y="36" width="460" height="46" rx="5" fill="#f0f9ff" stroke="#0284c7" stroke-width="2" />
          <text x="270" y="58" fill="#0284c7" font-size="12" font-weight="700" text-anchor="middle">Virtual Page Number (VPN)</text>
          <text x="270" y="73" fill="#0369a1" font-size="9.5" text-anchor="middle">Upper Address Bits [47:12] on x86-64 / [31:12] on 32-bit</text>

          <!-- Offset Box (Top) -->
          <rect x="520" y="36" width="320" height="46" rx="5" fill="#f8fafc" stroke="#64748b" stroke-width="2" />
          <text x="680" y="58" fill="#334155" font-size="12" font-weight="700" text-anchor="middle">Page Offset (12 bits)</text>
          <text x="680" y="73" fill="#64748b" font-size="9.5" text-anchor="middle">Bits [11:0] &bull; Identifies exact byte in 4 KiB page</text>

          <!-- Middle Translation Unit -->
          <!-- VPN down into MMU lookup -->
          <path d="M 270,82 L 270,108" fill="none" stroke="#0284c7" stroke-width="2" marker-end="url(#arrowBlue)" />

          <!-- MMU Page Table Box -->
          <rect x="180" y="112" width="180" height="34" rx="4" fill="#0284c7" stroke="#0369a1" stroke-width="1.5" />
          <text x="270" y="133" fill="#ffffff" font-size="11" font-weight="700" text-anchor="middle">Page Table Lookup</text>

          <!-- Translated PFN emerging down to shifted physical box -->
          <path d="M 270,146 L 270,188" fill="none" stroke="#059669" stroke-width="2" marker-end="url(#arrowGreen)" />

          <!-- Unmodified Offset Pass-Through Line -->
          <path d="M 680,82 L 680,188" fill="none" stroke="#64748b" stroke-width="2" stroke-dasharray="6,4" marker-end="url(#arrowGray)" />
          <text x="692" y="138" fill="#64748b" font-size="9.5" font-style="italic">Passes through unchanged</text>

          <!-- Bottom Label (Shifted Down) -->
          <text x="40" y="180" fill="#0f172a" font-size="12" font-weight="700">PHYSICAL ADDRESS (Issued to DRAM Memory Bus)</text>

          <!-- Physical Address Split Boxes (Shifted Down to y=194) -->
          <!-- PFN Box -->
          <rect x="40" y="194" width="460" height="46" rx="5" fill="#ecfdf5" stroke="#059669" stroke-width="2" />
          <text x="270" y="216" fill="#059669" font-size="12" font-weight="700" text-anchor="middle">Physical Frame Number (PFN)</text>
          <text x="270" y="231" fill="#065f46" font-size="9.5" text-anchor="middle">Base address of 4 KiB frame in physical DRAM</text>

          <!-- Offset Box (Bottom) -->
          <rect x="520" y="194" width="320" height="46" rx="5" fill="#f8fafc" stroke="#64748b" stroke-width="2" />
          <text x="680" y="216" fill="#334155" font-size="12" font-weight="700" text-anchor="middle">Page Offset (12 bits)</text>
          <text x="680" y="231" fill="#64748b" font-size="9.5" text-anchor="middle">Bits [11:0] &bull; Unmodified intra-frame byte offset</text>
        </svg>
      </div>
"""

def adjust_address_svg_spacing():
    file_path = os.path.join("week01-operating-system-concepts", "02-hardware-review.html")
    if not os.path.exists(file_path):
        print(f"Error: {file_path} not found.")
        return

    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    pattern = r'<div class="diagram-container"[^>]*>\s*<svg viewBox="0 0 880 230".*?</svg>\s*</div>'
    match = re.search(pattern, content, flags=re.DOTALL)

    if match:
        start, end = match.span()
        content = content[:start] + REFINED_ADDRESS_SPLIT_SVG.strip() + content[end:]
        print("--> Shifted physical address boxes down and expanded SVG height.")
    else:
        # Fallback if viewBox or class formatting differed
        fallback_pattern = r'<svg viewBox="0 0 880 2[3-9]0"[^>]*>.*?VIRTUAL ADDRESS.*?PHYSICAL ADDRESS.*?</svg>'
        fallback_match = re.search(fallback_pattern, content, flags=re.DOTALL)
        if fallback_match:
            start, end = fallback_match.span()
            content = content[:start] + REFINED_ADDRESS_SPLIT_SVG.strip() + content[end:]
            print("--> Shifted physical address boxes via fallback pattern.")
        else:
            print("--> Address split SVG not found.")
            return

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    try:
        subprocess.run(["git", "add", "fix.py", file_path], check=True)
        commit_msg = (
            "Shift physical address boxes downward in address translation SVG\n\n"
            "Increase vertical spacing and expand viewBox height to 260 in Module 2\n"
            "to prevent overlap between translation arrows and physical address boxes."
        )
        subprocess.run(["git", "commit", "-m", commit_msg], check=True)
        subprocess.run(["git", "push", "origin", "main"], check=True)
        print("--> Git sync completed successfully via fix.py!")
    except Exception as e:
        print(f"Git execution note: {e}")

if __name__ == "__main__":
    adjust_address_svg_spacing()
