#!/usr/bin/env python3
# =====================================================================
# fix.py: Replace text virtual address box with clean architectural SVG
# =====================================================================
import os
import re
import subprocess

ADDRESS_SPLIT_SVG = """
      <div class="diagram-container" style="margin: 24px 0;">
        <svg viewBox="0 0 880 230" width="100%" height="auto" style="max-width: 880px; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, monospace;" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <marker id="arrowBlue" markerWidth="6" markerHeight="6" refX="4" refY="3" orient="auto">
              <path d="M0,0 L6,3 L0,6 Z" fill="#0284c7" />
            </marker>
            <marker id="arrowGreen" markerWidth="6" markerHeight="6" refX="4" refY="3" orient="auto">
              <path d="M0,0 L6,3 L0,6 Z" fill="#059669" />
            </marker>
            <marker id="arrowGray" markerWidth="6" markerHeight="6" refX="4" refY="3" orient="auto">
              <path d="M0,0 L6,3 L0,6 Z" fill="#64748b" />
            </marker>
          </defs>

          <!-- Top Label -->
          <text x="40" y="24" fill="#0f172a" font-size="12" font-weight="700">VIRTUAL ADDRESS (Generated by CPU Instruction)</text>

          <!-- Virtual Address Split Boxes -->
          <!-- VPN Box -->
          <rect x="40" y="36" width="460" height="46" rx="5" fill="#f0f9ff" stroke="#0284c7" stroke-width="2" />
          <text x="270" y="58" fill="#0284c7" font-size="12" font-weight="700" text-anchor="middle">Virtual Page Number (VPN)</text>
          <text x="270" y="73" fill="#0369a1" font-size="9.5" text-anchor="middle">Upper Address Bits [47:12] on x86-64 / [31:12] on 32-bit</text>

          <!-- Offset Box (Top) -->
          <rect x="520" y="36" width="320" height="46" rx="5" fill="#f8fafc" stroke="#64748b" stroke-width="2" />
          <text x="680" y="58" fill="#334155" font-size="12" font-weight="700" text-anchor="middle">Page Offset (12 bits)</text>
          <text x="680" y="73" fill="#64748b" font-size="9.5" text-anchor="middle">Bits [11:0] &bull; Identifies exact byte in 4 KiB page</text>

          <!-- Middle Translation Unit -->
          <!-- VPN down into MMU lookup -->
          <path d="M 270,82 L 270,108" fill="none" stroke="#0284c7" stroke-width="2" marker-end="url(#arrowBlue)" />

          <!-- MMU Page Table Box -->
          <rect x="180" y="112" width="180" height="34" rx="4" fill="#0284c7" stroke="#0369a1" stroke-width="1.5" />
          <text x="270" y="133" fill="#ffffff" font-size="11" font-weight="700" text-anchor="middle">Page Table Lookup</text>

          <!-- Translated PFN emerging down -->
          <path d="M 270,146 L 270,166" fill="none" stroke="#059669" stroke-width="2" marker-end="url(#arrowGreen)" />

          <!-- Unmodified Offset Pass-Through Line -->
          <path d="M 680,82 L 680,166" fill="none" stroke="#64748b" stroke-width="2" stroke-dasharray="6,4" marker-end="url(#arrowGray)" />
          <text x="692" y="130" fill="#64748b" font-size="9.5" font-style="italic">Passes through unchanged</text>

          <!-- Bottom Label -->
          <text x="40" y="162" fill="#0f172a" font-size="12" font-weight="700">PHYSICAL ADDRESS (Issued to DRAM Memory Bus)</text>

          <!-- Physical Address Split Boxes -->
          <!-- PFN Box -->
          <rect x="40" y="172" width="460" height="46" rx="5" fill="#ecfdf5" stroke="#059669" stroke-width="2" />
          <text x="270" y="194" fill="#059669" font-size="12" font-weight="700" text-anchor="middle">Physical Frame Number (PFN)</text>
          <text x="270" y="209" fill="#065f46" font-size="9.5" text-anchor="middle">Base address of 4 KiB frame in physical DRAM</text>

          <!-- Offset Box (Bottom) -->
          <rect x="520" y="172" width="320" height="46" rx="5" fill="#f8fafc" stroke="#64748b" stroke-width="2" />
          <text x="680" y="194" fill="#334155" font-size="12" font-weight="700" text-anchor="middle">Page Offset (12 bits)</text>
          <text x="680" y="209" fill="#64748b" font-size="9.5" text-anchor="middle">Bits [11:0] &bull; Unmodified intra-frame byte offset</text>
        </svg>
      </div>
"""

def substitute_address_text_block():
    file_path = os.path.join("week01-operating-system-concepts", "02-hardware-review.html")
    if not os.path.exists(file_path):
        print(f"Error: {file_path} not found.")
        return

    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Pattern targeting the preformatted / styled text box containing the address layout
    text_pattern = r'<div style="background:\s*#0f172a;[^>]*>.*?Virtual Address:.*?Physical Address:.*?</div>'
    match = re.search(text_pattern, content, flags=re.DOTALL)

    if match:
        start, end = match.span()
        content = content[:start] + ADDRESS_SPLIT_SVG.strip() + content[end:]
        print("--> Replaced preformatted virtual address text with clean SVG vector diagram.")
    else:
        # Fallback search if style attribute varied
        fallback_pattern = r'Virtual Address:\s*\[\s*Virtual Page Number.*?Physical Address:\s*\[\s*Physical Frame Number.*?</div>'
        fallback_match = re.search(fallback_pattern, content, flags=re.DOTALL)
        if fallback_match:
            # Expand to surrounding div
            div_start = content.rfind("<div", 0, fallback_match.start())
            div_end = content.find("</div>", fallback_match.end()) + 6
            content = content[:div_start] + ADDRESS_SPLIT_SVG.strip() + content[div_end:]
            print("--> Replaced virtual address block via fallback pattern.")
        else:
            print("--> Could not locate virtual address text block.")
            return

    with open(file_path, "w", encoding="utf-8") as f:
        f.write(content)

    try:
        subprocess.run(["git", "add", "fix.py", file_path], check=True)
        commit_msg = (
            "Replace preformatted virtual address block with clean vector SVG\n\n"
            "Convert text mapping of VPN/PFN and 12-bit offset in Section 3 of\n"
            "week01-operating-system-concepts/02-hardware-review.html to an SVG diagram."
        )
        subprocess.run(["git", "commit", "-m", commit_msg], check=True)
        subprocess.run(["git", "push", "origin", "main"], check=True)
        print("--> Git sync completed successfully via fix.py!")
    except Exception as e:
        print(f"Git execution note: {e}")

if __name__ == "__main__":
    substitute_address_text_block()
